#!/bin/sh

pre_checks() {
  mmc=$(sysctl vm.max_map_count|sed 's/.*= //')
  if [[ $mmc -lt 262144 ]]; then
    echo "
ERROR: As of 5.0.0 Elasticsearch requires increasing mmap counts.
Refer to https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
"
    sysctl -w vm.max_map_count=262144
  fi
}

discoverIpFromLink() {
  dev=$1
  mode=$2
  ip=`ipaddr show dev $dev scope global|awk '$1 == "inet" { if (!match($2,"/32")) { gsub("/.*","",$2) ; print $2 } }'`
  echo "Discovered $mode address $ip for $dev"
  OPTS="$OPTS -D$mode.host=$ip"
}

discoverAllGlobalIps() {
  if [ ${#IGNORE_NETWORK} -eq 0 ]
  then
    IGNORE_NETWORK='999.999.999.999'
  fi
  printf "Finding IPs"
  while [ ${#ips} -eq 0 ]
  do
    printf "."
    ips=`ipaddr show scope global| grep -v "inet ${IGNORE_NETWORK}" | awk '$1 == "inet" { if (!match($2,"/32")) { gsub("/.*","",$2) ; addrs[length(addrs)] = $2 } } END { for (i in addrs) { if (i>0) printf "," ; printf addrs[i] } }'`
    sleep 1
  done
  echo " found! $ips"
  OPTS="$OPTS -Dnetwork.host=$ips"
}

setup_clustering() {

  if [ -n "$CLUSTER" ]; then
    OPTS="$OPTS -Dcluster.name=$CLUSTER"
    if [ -n "$CLUSTER_FROM" ]; then
      if [ -d /data/$CLUSTER_FROM -a ! -d /data/$CLUSTER ]; then
        echo "Performing cluster data migration from $CLUSTER_FROM to $CLUSTER"
        mv /data/$CLUSTER_FROM /data/$CLUSTER
      fi
    fi
  fi

  if [ -n "$NODE_NAME" ]; then
    OPTS="$OPTS -Dnode.name=$NODE_NAME"
  fi

  if [ -n "$MULTICAST" ]; then
    OPTS="$OPTS -Ddiscovery.zen.ping.multicast.enabled=$MULTICAST"
  fi

  if [ -n "$UNICAST_HOSTS" ]; then
    OPTS="$OPTS -Ddiscovery.zen.ping.unicast.hosts=$UNICAST_HOSTS"
  fi

  if [ -n "$PUBLISH_AS" ]; then
    OPTS="$OPTS -Dtransport.publish_host=$(echo $PUBLISH_AS | awk -F: '{print $1}')"
    OPTS="$OPTS -Dtransport.publish_port=$(echo $PUBLISH_AS | awk -F: '{if ($2) print $2; else print 9300}')"
  fi

  if [ -n "$MIN_MASTERS" ]; then
    OPTS="$OPTS -Ddiscovery.zen.minimum_master_nodes=$MIN_MASTERS"
  fi

}

install_plugins() {

  if [ -n "$PLUGINS" ]; then
    for p in $(echo $PLUGINS | awk -v RS=, '{print}')
    do
      echo "Installing the plugin $p"
      $ES_HOME/bin/plugin install $p
    done
  else
    mkdir -p $ES_HOME/plugins
  fi
}

setup_personality() {

  if [ -n "$TYPE" ]; then
    case $TYPE in
      MASTER)
        OPTS="$OPTS -Dnode.master=true -Dnode.data=false -Dnode.ingest=false"
        ;;

      GATEWAY|COORDINATING)
        OPTS="$OPTS -Dnode.master=false -Dnode.data=false -Dnode.ingest=false"
        ;;

      INGEST)
        OPTS="$OPTS -Dnode.master=false -Dnode.data=false -Dnode.ingest=true"
        ;;

      DATA)
        OPTS="$OPTS -Dnode.master=false -Dnode.data=true -Dnode.ingest=false"
        ;;

      NON_MASTER)
        OPTS="$OPTS -Dnode.master=false -Dnode.data=true -Dnode.ingest=true"
        ;;

      NON_DATA)
        OPTS="$OPTS -Dnode.master=true -Dnode.data=false -Dnode.ingest=true"
        ;;

      *)
        echo "Unknown node type. Please use MASTER|GATEWAY|DATA|NON_MASTER"
        exit 1
    esac
  fi

}

pre_checks

#do not set env from file
if [ -f /conf/env ]; then
  . /conf/env
fi

if [ ! -e /conf/elasticsearch.* ]; then
  cp $ES_HOME/config/elasticsearch.yml /conf
fi

if [ ! -e /conf/log4j2.properties ]; then
  cp $ES_HOME/config/log4j2.properties /conf
fi

OPTS="$OPTS \
  -Dpath.conf=/conf \
  -Dpath.data=/data \
  -Dpath.logs=/logs \
  -Dtransport.tcp.port=9300 \
  -Dhttp.port=9200"

discoverAllGlobalIps
if [ "${DISCOVER_TRANSPORT_IP}" != "" ]; then
  discoverIpFromLink $DISCOVER_TRANSPORT_IP transport
fi
if [ "${DISCOVER_HTTP_IP}" != "" ]; then
  discoverIpFromLink $DISCOVER_HTTP_IP http
fi

setup_personality
setup_clustering
install_plugins

mkdir -p /conf/scripts

echo "Starting Elasticsearch with the options $OPTS"
env
CMD="cd $ES_HOME/bin && ./elasticsearch.in.sh && ./elasticsearch $OPTS"
if [ `id -u` = 0 ]; then
  echo "Running as non-root..."
  chown -R $DEFAULT_ES_USER /data /conf /logs
  su -c "$CMD" $DEFAULT_ES_USER
else
  $CMD
fi
